//! A test-only CHD v5 CD writer over synthetic tracks, and Redump-style bin and cue sets for
//! chdman; see `docs/CHD.md` and `docs/TESTING.md` "CHD images".

mod flac;
mod huffman;
mod map;
mod sector;

use std::collections::HashMap;
use std::fs;
use std::io::{self, Cursor, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use flate2::write::DeflateEncoder;
use flate2::Compression;
use mistarr_core::chd::{crc16, ecc};
use mistarr_core::hash::{hash_reader, HeaderRule};
use mistarr_core::HashSet;
use sha1::{Digest as _, Sha1};

use crate::rng::SplitMix;
use map::Entry;

const FRAME: usize = 2448;
const SECTOR: usize = 2352;
const SUBCODE: usize = 96;

/// How a synthetic track's sectors are stored.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// Raw Mode 1 sectors.
    Mode1Raw,
    /// Raw Mode 2 Form 1 sectors.
    Mode2Raw,
    /// CD audio.
    Audio,
    /// Mode 1 stored as 2048-byte cooked sectors.
    Mode1Cooked,
}

impl Kind {
    fn cht2(self) -> &'static str {
        match self {
            Self::Mode1Raw => "MODE1_RAW",
            Self::Mode2Raw => "MODE2_RAW",
            Self::Audio => "AUDIO",
            Self::Mode1Cooked => "MODE1",
        }
    }

    fn cue(self) -> &'static str {
        match self {
            Self::Mode1Raw => "MODE1/2352",
            Self::Mode2Raw => "MODE2/2352",
            Self::Audio => "AUDIO",
            Self::Mode1Cooked => "MODE1/2048",
        }
    }
}

/// One track: `frames` from INDEX 01, after `pregap` frames from INDEX 00.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TrackSpec {
    /// Sector format.
    pub kind: Kind,
    /// Frames from INDEX 01 to the end of the track.
    pub frames: u32,
    /// Frames between INDEX 00 and INDEX 01.
    pub pregap: u32,
    /// Whether the pregap is stored in the image (a `V` pregap type).
    pub pregap_stored: bool,
}

/// A hunk codec.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Codec {
    /// `cdlz`: LZMA sectors, deflate subcode.
    CdLzma,
    /// `cdzl`: deflate sectors and subcode.
    CdZlib,
    /// `cdzs`: zstd sectors and subcode.
    CdZstd,
    /// `cdfl`: FLAC sectors, deflate subcode.
    CdFlac,
    /// `zlib` over the whole hunk.
    Zlib,
    /// `lzma` over the whole hunk.
    Lzma,
    /// `zstd` over the whole hunk.
    Zstd,
    /// `flac` over the whole hunk.
    Flac,
    /// `huff`: named in a slot, with a payload no decoder should read.
    Huff,
}

impl Codec {
    fn fourcc(self) -> [u8; 4] {
        *match self {
            Self::CdLzma => b"cdlz",
            Self::CdZlib => b"cdzl",
            Self::CdZstd => b"cdzs",
            Self::CdFlac => b"cdfl",
            Self::Zlib => b"zlib",
            Self::Lzma => b"lzma",
            Self::Zstd => b"zstd",
            Self::Flac => b"flac",
            Self::Huff => b"huff",
        }
    }
}

/// How a codec is chosen for each hunk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Pick {
    /// Slot `hunk % slots`, falling back to the next that can code it.
    Cycle,
    /// The smallest result, as chdman does.
    Smallest,
}

/// The map's Huffman tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tree {
    /// Every type 4 bits long.
    Uniform,
    /// A length-limited tree built from the type histogram.
    Built,
}

/// What to write.
#[derive(Debug, Clone)]
pub struct Spec {
    /// Seeds every generated byte.
    pub label: String,
    /// The tracks in order.
    pub tracks: Vec<TrackSpec>,
    /// Frames per hunk.
    pub frames_per_hunk: u32,
    /// Codec slots, at most 4; empty writes an uncompressed image.
    pub codecs: Vec<Codec>,
    /// How each hunk's codec is chosen.
    pub pick: Pick,
    /// The map tree.
    pub tree: Tree,
    /// Fill subcode with pseudo-random bytes instead of zeros, except behind silence.
    pub subcode: bool,
    /// Store a hunk equal to an earlier one as a copy.
    pub self_refs: bool,
    /// Run-length code repeated hunk types in the map.
    pub rle_types: bool,
    /// Give every n-th data sector a wrong P parity byte.
    pub bad_ecc_every: Option<u32>,
    /// Metadata tag of the track entries.
    pub track_tag: [u8; 4],
    /// Parent SHA1 written to the header.
    pub parent: Option<[u8; 20]>,
}

impl Spec {
    /// A spec with chdman's default codecs, 8-frame hunks and a built tree.
    ///
    /// ```
    /// use mistarr_fixture::chd::{Kind, Spec, TrackSpec};
    /// let s = Spec::new("disc", vec![TrackSpec { kind: Kind::Audio, frames: 4, pregap: 0, pregap_stored: true }]);
    /// assert_eq!(s.frames_per_hunk, 8);
    /// ```
    #[must_use]
    pub fn new(label: &str, tracks: Vec<TrackSpec>) -> Self {
        Self {
            label: label.to_owned(),
            tracks,
            frames_per_hunk: 8,
            codecs: vec![Codec::CdLzma, Codec::CdZlib, Codec::CdFlac],
            pick: Pick::Smallest,
            tree: Tree::Built,
            subcode: false,
            self_refs: true,
            rle_types: true,
            bad_ecc_every: None,
            track_tag: *b"CHT2",
            parent: None,
        }
    }

    /// Sectors in track `t`'s Redump-style `.bin`.
    fn bin_len(&self, t: usize) -> u32 {
        self.tracks[t].frames + self.tracks[t].pregap
    }

    /// Sectors of track `t` stored in the image.
    fn stored_len(&self, t: usize) -> u32 {
        let s = &self.tracks[t];
        if s.pregap_stored {
            s.frames + s.pregap
        } else {
            s.frames
        }
    }

    /// The `.bin` sector `i` of track `t`, little-endian audio, 2048 bytes when cooked.
    fn bin_sector(&self, t: usize, i: u32) -> Vec<u8> {
        let s = &self.tracks[t];
        let lba: u32 = (0..t).map(|p| self.bin_len(p)).sum::<u32>() + i;
        let mut rng = SplitMix::from_label(&format!("{}/{t}/{i}", self.label));
        if s.kind == Kind::Audio {
            if i < s.pregap {
                return vec![0u8; SECTOR];
            }
            return sector::audio(&mut rng, i64::from(lba) * 588).to_vec();
        }
        let data = if i < s.pregap {
            [0u8; 2048]
        } else {
            sector::user_data(&mut rng, i)
        };
        let mut out = match s.kind {
            Kind::Mode2Raw => sector::mode2_form1(lba, &data),
            Kind::Mode1Cooked => return data.to_vec(),
            _ => sector::mode1(lba, &data),
        };
        if self
            .bad_ecc_every
            .is_some_and(|n| n > 0 && (i + 1).is_multiple_of(n))
        {
            out[0x81c] ^= 0xff;
        }
        out.to_vec()
    }

    /// The image frame for stored sector `i` of track `t`, subcode included.
    fn chd_frame(&self, t: usize, i: u32, global: u64) -> [u8; FRAME] {
        let s = &self.tracks[t];
        let skip = if s.pregap_stored { 0 } else { s.pregap };
        let bin = self.bin_sector(t, i + skip);
        let mut f = [0u8; FRAME];
        if s.kind == Kind::Audio {
            for (o, p) in f[..SECTOR]
                .as_chunks_mut::<2>()
                .0
                .iter_mut()
                .zip(bin.as_chunks::<2>().0)
            {
                o[0] = p[1];
                o[1] = p[0];
            }
        } else {
            f[..bin.len()].copy_from_slice(&bin);
        }
        if self.subcode && bin.iter().any(|&b| b != 0) {
            let mut rng = SplitMix::from_label(&format!("{}/sub/{global}", self.label));
            f[SECTOR..].copy_from_slice(&rng.bytes(SUBCODE));
        }
        f
    }

    fn cht2(&self, t: usize) -> String {
        let s = &self.tracks[t];
        let pgtype = if s.pregap_stored && s.pregap > 0 {
            format!("V{}", s.kind.cht2())
        } else {
            s.kind.cht2().to_owned()
        };
        format!(
            "TRACK:{} TYPE:{} SUBTYPE:NONE FRAMES:{} PREGAP:{} PGTYPE:{pgtype} PGSUB:RW POSTGAP:0",
            t + 1,
            s.kind.cht2(),
            self.stored_len(t),
            s.pregap
        )
    }

    /// Every image frame in order, pad frames included.
    fn frames(&self) -> impl Iterator<Item = [u8; FRAME]> + '_ {
        let mut global = 0u64;
        (0..self.tracks.len()).flat_map(move |t| {
            let n = self.stored_len(t);
            let pad = (4 - n % 4) % 4;
            let start = global;
            global += u64::from(n + pad);
            (0..n + pad).map(move |i| {
                if i < n {
                    self.chd_frame(t, i, start + u64::from(i))
                } else {
                    [0u8; FRAME]
                }
            })
        })
    }

    fn total_frames(&self) -> u64 {
        (0..self.tracks.len())
            .map(|t| {
                let n = self.stored_len(t);
                u64::from(n + (4 - n % 4) % 4)
            })
            .sum()
    }
}

/// What [`write`] produced.
#[derive(Debug, Clone)]
pub struct Written {
    /// File size.
    pub size: u64,
    /// Hashes of each track's `.bin`, computed from the bin bytes rather than the image.
    pub tracks: Vec<HashSet>,
    /// SHA1 of the decoded image data.
    pub raw_sha1: [u8; 20],
    /// Combined SHA1 of the raw SHA1 and the checksummed metadata.
    pub sha1: [u8; 20],
    /// Hunks stored with each codec.
    pub codec_use: Vec<(Codec, u32)>,
}

fn deflate(data: &[u8]) -> Vec<u8> {
    let mut e = DeflateEncoder::new(Vec::new(), Compression::best());
    // Writing to a Vec cannot fail.
    let _ = e.write_all(data);
    e.finish().unwrap_or_default()
}

fn lzma(data: &[u8]) -> Vec<u8> {
    let opts = lzma_rs::compress::Options {
        unpacked_size: lzma_rs::compress::UnpackedSize::WriteToHeader(Some(data.len() as u64)),
    };
    let mut out = Vec::new();
    let _ = lzma_rs::lzma_compress_with_options(&mut &data[..], &mut out, &opts);
    out.split_off(13.min(out.len()))
}

/// A zstd frame: a hand-built single-segment frame with a content size and one RLE block
/// when every byte is equal, otherwise ruzstd's windowed frame without a content size.
fn zstd(data: &[u8]) -> Vec<u8> {
    let same = data.first().is_some_and(|&b| data.iter().all(|&x| x == b));
    if same && data.len() < (128 << 10) {
        let len = u32::try_from(data.len()).unwrap_or(0);
        let mut f = vec![0x28, 0xb5, 0x2f, 0xfd, 0xa0];
        f.extend_from_slice(&len.to_le_bytes());
        f.extend_from_slice(&((len << 3) | 0b011).to_le_bytes()[..3]);
        f.push(data[0]);
        return f;
    }
    ruzstd::encoding::compress_to_vec(data, ruzstd::encoding::CompressionLevel::Fastest)
}

/// MAME's FLAC block size: a quarter of the bytes, halved until at most `limit`.
fn flac_block(bytes: usize, limit: usize) -> usize {
    let mut b = bytes / 4;
    while b > limit {
        b /= 2;
    }
    b
}

/// The CD front end of `cdlz`, `cdzl` and `cdzs`, or `None` when the base does not fit its
/// length field.
fn cd_hunk(codec: Codec, hunk: &[u8]) -> Option<Vec<u8>> {
    let frames = hunk.len() / FRAME;
    let mut flags = vec![0u8; frames.div_ceil(8)];
    let mut base = Vec::with_capacity(frames * SECTOR);
    let mut sub = Vec::with_capacity(frames * SUBCODE);
    for (f, frame) in hunk.as_chunks::<FRAME>().0.iter().enumerate() {
        let mut sector: [u8; SECTOR] = frame[..SECTOR].try_into().ok()?;
        if sector[..12] == sector::SYNC && ecc::verify(&sector) {
            flags[f / 8] |= 1 << (f % 8);
            sector[..12].fill(0);
            sector[0x81c..].fill(0);
        }
        base.extend_from_slice(&sector);
        sub.extend_from_slice(&frame[SECTOR..]);
    }
    let (b, s) = match codec {
        Codec::CdLzma => (lzma(&base), deflate(&sub)),
        Codec::CdZstd => (zstd(&base), zstd(&sub)),
        _ => (deflate(&base), deflate(&sub)),
    };
    let len_bytes = if hunk.len() < 65_536 { 2 } else { 3 };
    if b.len() >= 1 << (8 * len_bytes) {
        return None;
    }
    let mut out = flags;
    out.extend_from_slice(&u32::try_from(b.len()).ok()?.to_be_bytes()[4 - len_bytes..]);
    out.extend_from_slice(&b);
    out.extend_from_slice(&s);
    Some(out)
}

fn compress(codec: Codec, hunk: &[u8]) -> Option<Vec<u8>> {
    Some(match codec {
        Codec::Zlib => deflate(hunk),
        Codec::Lzma => lzma(hunk),
        Codec::Zstd => zstd(hunk),
        Codec::Flac => {
            let mut out = vec![b'B'];
            out.extend(flac::encode(
                &flac::samples_be(hunk),
                flac_block(hunk.len(), 2048),
            ));
            out
        }
        Codec::CdFlac => {
            let frames = hunk.len() / FRAME;
            let mut base = Vec::with_capacity(frames * SECTOR);
            let mut sub = Vec::with_capacity(frames * SUBCODE);
            for frame in hunk.as_chunks::<FRAME>().0 {
                base.extend_from_slice(&frame[..SECTOR]);
                sub.extend_from_slice(&frame[SECTOR..]);
            }
            let mut out = flac::encode(&flac::samples_be(&base), flac_block(base.len(), SECTOR));
            out.extend(deflate(&sub));
            out
        }
        Codec::Huff => vec![0xa5; 16],
        cd => return cd_hunk(cd, hunk),
    })
}

/// The codec slot and payload for one hunk, or `None` to store it as is.
fn choose(spec: &Spec, index: u64, hunk: &[u8]) -> Option<(u8, Vec<u8>)> {
    let n = spec.codecs.len();
    let tries: Vec<usize> = match spec.pick {
        Pick::Cycle => (0..n)
            .map(|k| (usize::try_from(index).unwrap_or(0) + k) % n)
            .collect(),
        Pick::Smallest => (0..n).filter(|&k| spec.codecs[k] != Codec::Huff).collect(),
    };
    let mut best: Option<(u8, Vec<u8>)> = None;
    for k in tries {
        let Some(out) = compress(spec.codecs[k], hunk) else {
            continue;
        };
        if out.len() >= hunk.len() && spec.codecs[k] != Codec::Huff {
            continue;
        }
        let slot = u8::try_from(k).unwrap_or(0);
        if spec.pick == Pick::Cycle {
            return Some((slot, out));
        }
        if best.as_ref().is_none_or(|(_, b)| out.len() < b.len()) {
            best = Some((slot, out));
        }
    }
    best
}

fn metadata(spec: &Spec, at: u64) -> (Vec<u8>, Vec<[u8; 24]>) {
    let mut out = Vec::new();
    let mut records = Vec::new();
    for t in 0..spec.tracks.len() {
        let mut text = spec.cht2(t).into_bytes();
        text.push(0);
        let next = if t + 1 == spec.tracks.len() {
            0
        } else {
            at + out.len() as u64 + 16 + text.len() as u64
        };
        out.extend_from_slice(&spec.track_tag);
        out.push(1);
        out.extend_from_slice(&u32::try_from(text.len()).unwrap_or(0).to_be_bytes()[1..]);
        out.extend_from_slice(&next.to_be_bytes());
        out.extend_from_slice(&text);
        let mut rec = [0u8; 24];
        rec[..4].copy_from_slice(&spec.track_tag);
        rec[4..].copy_from_slice(&Sha1::digest(&text));
        records.push(rec);
    }
    (out, records)
}

/// Hunk entries, codec use and raw SHA1 of the hunks written so far.
struct Hunks {
    entries: Vec<Entry>,
    plain: Vec<u32>,
    uses: HashMap<Codec, u32>,
    raw: Sha1,
}

/// Writes every hunk of `spec` from the current position of `w`.
fn write_hunks<W: Write + Seek>(spec: &Spec, w: &mut W, logical: u64) -> io::Result<Hunks> {
    let hunk_bytes = spec.frames_per_hunk as usize * FRAME;
    let compressed = !spec.codecs.is_empty();
    let mut out = Hunks {
        entries: Vec::new(),
        plain: Vec::new(),
        uses: HashMap::new(),
        raw: Sha1::new(),
    };
    let mut seen: HashMap<[u8; 20], u32> = HashMap::new();
    let mut frames = spec.frames();
    for index in 0..logical.div_ceil(hunk_bytes as u64) {
        let mut hunk = vec![0u8; hunk_bytes];
        for chunk in hunk.as_chunks_mut::<FRAME>().0 {
            if let Some(f) = frames.next() {
                chunk.copy_from_slice(&f);
            }
        }
        let left = logical - index * hunk_bytes as u64;
        out.raw
            .update(&hunk[..usize::try_from(left).unwrap_or(hunk_bytes).min(hunk_bytes)]);
        if !compressed {
            if spec.self_refs && hunk.iter().all(|&b| b == 0) {
                out.plain.push(0);
            } else {
                let at = w.stream_position()? / hunk_bytes as u64;
                out.plain.push(u32::try_from(at).unwrap_or(0));
                w.write_all(&hunk)?;
            }
            continue;
        }
        if spec.self_refs {
            let digest: [u8; 20] = Sha1::digest(&hunk).into();
            if let Some(&target) = seen.get(&digest) {
                out.entries.push(Entry::Copy { target });
                continue;
            }
            seen.insert(digest, u32::try_from(index).unwrap_or(0));
        }
        let crc = crc16(&hunk);
        if let Some((slot, data)) = choose(spec, index, &hunk) {
            *out.uses.entry(spec.codecs[usize::from(slot)]).or_default() += 1;
            let len = u32::try_from(data.len()).unwrap_or(0);
            out.entries.push(Entry::Codec { slot, len, crc });
            w.write_all(&data)?;
        } else {
            out.entries.push(Entry::None { crc });
            w.write_all(&hunk)?;
        }
    }
    Ok(out)
}

/// The 124-byte v5 header.
fn header(
    spec: &Spec,
    logical: u64,
    map_offset: u64,
    meta_offset: u64,
    sums: ([u8; 20], [u8; 20]),
) -> [u8; 124] {
    let hunk_bytes = spec.frames_per_hunk * 2448;
    let mut head = [0u8; 124];
    head[..8].copy_from_slice(b"MComprHD");
    head[8..12].copy_from_slice(&124u32.to_be_bytes());
    head[12..16].copy_from_slice(&5u32.to_be_bytes());
    for (i, c) in spec.codecs.iter().take(4).enumerate() {
        head[16 + i * 4..20 + i * 4].copy_from_slice(&c.fourcc());
    }
    head[32..40].copy_from_slice(&logical.to_be_bytes());
    head[40..48].copy_from_slice(&map_offset.to_be_bytes());
    head[48..56].copy_from_slice(&meta_offset.to_be_bytes());
    head[56..60].copy_from_slice(&hunk_bytes.to_be_bytes());
    head[60..64].copy_from_slice(&2448u32.to_be_bytes());
    head[64..84].copy_from_slice(&sums.0);
    head[84..104].copy_from_slice(&sums.1);
    if let Some(p) = spec.parent {
        head[104..124].copy_from_slice(&p);
    }
    head
}

/// Writes the image of `spec` to `w`: header, metadata, hunks from the first stored offset,
/// then the map, with the header patched last.
///
/// # Errors
///
/// Any error writing to `w`.
pub fn write<W: Write + Seek>(spec: &Spec, mut w: W) -> io::Result<Written> {
    let hunk_bytes = u64::from(spec.frames_per_hunk) * FRAME as u64;
    let logical = spec.total_frames() * FRAME as u64;
    let hunk_count = logical.div_ceil(hunk_bytes);
    let compressed = !spec.codecs.is_empty();
    w.write_all(&[0u8; 124])?;
    let meta_at = if compressed {
        124
    } else {
        124 + 4 * hunk_count
    };
    w.write_all(&vec![0u8; usize::try_from(meta_at - 124).unwrap_or(0)])?;
    let (meta, mut records) = metadata(spec, meta_at);
    w.write_all(&meta)?;
    let first = w.stream_position()?;
    if !compressed {
        let pad = first.next_multiple_of(hunk_bytes) - first;
        w.write_all(&vec![0u8; usize::try_from(pad).unwrap_or(0)])?;
    }
    let hunks = write_hunks(spec, &mut w, logical)?;
    let map_offset = w.stream_position()?;
    if compressed {
        let hb = u32::try_from(hunk_bytes).unwrap_or(0);
        w.write_all(&map::encode(
            &hunks.entries,
            first,
            hb,
            spec.tree,
            spec.rle_types,
        ))?;
    } else {
        w.seek(SeekFrom::Start(124))?;
        for e in &hunks.plain {
            w.write_all(&e.to_be_bytes())?;
        }
        w.seek(SeekFrom::Start(map_offset))?;
    }
    let size = w.stream_position()?;

    let raw_sha1: [u8; 20] = hunks.raw.finalize().into();
    records.sort_unstable();
    let mut all = Sha1::new();
    all.update(raw_sha1);
    for r in &records {
        all.update(r);
    }
    let sha1: [u8; 20] = all.finalize().into();
    let map_at = if compressed { map_offset } else { 124 };
    w.seek(SeekFrom::Start(0))?;
    w.write_all(&header(spec, logical, map_at, meta_at, (raw_sha1, sha1)))?;
    w.seek(SeekFrom::Start(size))?;

    let tracks = (0..spec.tracks.len())
        .map(|t| hash_reader(track_bin(spec, t), HeaderRule::None, None))
        .collect::<io::Result<Vec<_>>>()?;
    let mut codec_use: Vec<(Codec, u32)> = hunks.uses.into_iter().collect();
    codec_use.sort_by_key(|(c, _)| c.fourcc());
    Ok(Written {
        size,
        tracks,
        raw_sha1,
        sha1,
        codec_use,
    })
}

/// The image of `spec` in memory.
///
/// # Errors
///
/// Never in practice: writing to memory does not fail.
///
/// ```
/// use mistarr_fixture::chd::{to_vec, Kind, Spec, TrackSpec};
/// let spec = Spec::new("doc", vec![TrackSpec { kind: Kind::Mode1Raw, frames: 3, pregap: 0, pregap_stored: true }]);
/// let (bytes, written) = to_vec(&spec).unwrap();
/// assert_eq!(bytes.len() as u64, written.size);
/// assert_eq!(&bytes[..8], b"MComprHD");
/// ```
pub fn to_vec(spec: &Spec) -> io::Result<(Vec<u8>, Written)> {
    let mut c = Cursor::new(Vec::new());
    let w = write(spec, &mut c)?;
    Ok((c.into_inner(), w))
}

/// The Redump-style `.bin` of track `track`: every sector from INDEX 00, audio little-endian.
///
/// ```
/// use mistarr_fixture::chd::{track_bin, Kind, Spec, TrackSpec};
/// use std::io::Read;
/// let spec = Spec::new("doc", vec![TrackSpec { kind: Kind::Audio, frames: 2, pregap: 1, pregap_stored: true }]);
/// let mut bin = Vec::new();
/// track_bin(&spec, 0).read_to_end(&mut bin).unwrap();
/// assert_eq!(bin.len(), 3 * 2352);
/// ```
#[must_use]
pub fn track_bin(spec: &Spec, track: usize) -> impl Read + '_ {
    TrackBin {
        spec,
        track,
        next: 0,
        buf: Cursor::new(Vec::new()),
    }
}

/// Streams one track's `.bin` a sector at a time.
struct TrackBin<'a> {
    spec: &'a Spec,
    track: usize,
    next: u32,
    buf: Cursor<Vec<u8>>,
}

impl Read for TrackBin<'_> {
    fn read(&mut self, out: &mut [u8]) -> io::Result<usize> {
        loop {
            let got = self.buf.read(out)?;
            if got > 0 || out.is_empty() || self.next >= self.spec.bin_len(self.track) {
                return Ok(got);
            }
            self.buf = Cursor::new(self.spec.bin_sector(self.track, self.next));
            self.next += 1;
        }
    }
}

/// Writes Redump-style source bins and a cue (split, or one file) for chdman; returns the cue
/// path. A pregap that is not stored becomes a cue `PREGAP` and is left out of the bin.
///
/// # Errors
///
/// Any error creating or writing the files.
pub fn write_redump_set(spec: &Spec, dir: &Path, single_file: bool) -> io::Result<PathBuf> {
    use std::fmt::Write as _;
    fs::create_dir_all(dir)?;
    let mut cue = String::new();
    let single = format!("{}.bin", spec.label);
    let mut single_out = None;
    if single_file {
        single_out = Some(io::BufWriter::new(fs::File::create(dir.join(&single))?));
        let _ = writeln!(cue, "FILE \"{single}\" BINARY");
    }
    let mut offset = 0u32;
    for (t, s) in spec.tracks.iter().enumerate() {
        let skip = if s.pregap_stored { 0 } else { s.pregap };
        let mut own = None;
        if !single_file {
            let name = format!("{} (Track {:02}).bin", spec.label, t + 1);
            let _ = writeln!(cue, "FILE \"{name}\" BINARY");
            own = Some(io::BufWriter::new(fs::File::create(dir.join(&name))?));
        }
        for i in skip..spec.bin_len(t) {
            let sector = spec.bin_sector(t, i);
            match (own.as_mut(), single_out.as_mut()) {
                (Some(w), _) | (None, Some(w)) => w.write_all(&sector)?,
                (None, None) => {}
            }
        }
        if let Some(mut w) = own {
            w.flush()?;
        }
        let base = if single_file { offset } else { 0 };
        let _ = writeln!(cue, "  TRACK {:02} {}", t + 1, s.kind.cue());
        if s.pregap > 0 && s.pregap_stored {
            let _ = writeln!(cue, "    INDEX 00 {}", sector::cue_time(base));
            let _ = writeln!(cue, "    INDEX 01 {}", sector::cue_time(base + s.pregap));
        } else {
            if s.pregap > 0 {
                let _ = writeln!(cue, "    PREGAP {}", sector::cue_time(s.pregap));
            }
            let _ = writeln!(cue, "    INDEX 01 {}", sector::cue_time(base));
        }
        offset += spec.bin_len(t) - skip;
    }
    if let Some(mut w) = single_out {
        w.flush()?;
    }
    let path = dir.join(format!("{}.cue", spec.label));
    fs::write(&path, cue)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn track(kind: Kind, frames: u32, pregap: u32) -> TrackSpec {
        TrackSpec {
            kind,
            frames,
            pregap,
            pregap_stored: true,
        }
    }

    #[test]
    fn layout_pads_tracks_to_four_frames() {
        let spec = Spec::new(
            "pad",
            vec![track(Kind::Mode1Raw, 5, 0), track(Kind::Audio, 3, 2)],
        );
        assert_eq!(spec.total_frames(), 8 + 8);
        assert_eq!(spec.frames().count(), 16);
        assert!(spec.cht2(1).contains("FRAMES:5 PREGAP:2 PGTYPE:VAUDIO"));
    }

    #[test]
    fn a_redump_set_splits_tracks_at_index_00() {
        let dir = tempfile::tempdir().expect("tmp");
        let spec = Spec::new(
            "Synthetic Disc",
            vec![track(Kind::Mode1Raw, 3, 0), track(Kind::Audio, 2, 150)],
        );
        let cue = write_redump_set(&spec, dir.path(), false).expect("set");
        let text = fs::read_to_string(&cue).expect("cue");
        assert!(text.contains("TRACK 02 AUDIO\n    INDEX 00 00:00:00\n    INDEX 01 00:02:00"));
        let bin2 = fs::read(dir.path().join("Synthetic Disc (Track 02).bin")).expect("bin");
        assert_eq!(bin2.len(), 152 * 2352);
        let single = write_redump_set(&spec, &dir.path().join("one"), true).expect("single");
        let text = fs::read_to_string(single).expect("cue");
        assert!(text.contains("INDEX 00 00:00:03\n    INDEX 01 00:02:03"));
    }

    #[test]
    fn the_lzma_stream_has_no_header() {
        let packed = lzma(&[7u8; 1000]);
        assert_eq!(
            packed[0], 0,
            "a raw stream starts with the range coder's zero byte"
        );
    }

    #[test]
    fn flac_block_sizes_follow_mame() {
        assert_eq!(flac_block(8 * 2352, 2352), 2352);
        assert_eq!(flac_block(27 * 2352, 2352), 1984);
        assert_eq!(flac_block(19584, 2048), 1224);
    }
}
